### ISSUE TITLE
Review: User Auth

### ISSUE THREAD

**Issue by david-dickinson** [dball1126/Yap#1]
- [x] Images do not currently load
- [ ] Styling is not yet exact (fonts, sizes, padding, etc)
- [x] Render errors for user to see
- [x] User interaction cannot yet log in / sign up / log out
- [x] Include demo user

**Comment by david-dickinson** [comment]
- [ ] Render errors the same way Yelp renders errors
- [ ] Match fonts with original (sans-serif)

**Comment by dball1126** [comment]
Errors render in almost an exact way now.   Font does match now, but it is not Sans serif
